package proyectoso;

import java.awt.AWTException;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Random;
import java.util.concurrent.Executors;
import java.util.concurrent.ScheduledExecutorService;
import java.util.concurrent.TimeUnit;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

public class Proyecto extends javax.swing.JFrame {

    public ArrayList<proceso> procesos = new ArrayList<>();
    List<String> procesosLista = new ArrayList<String>();
    public int contadorProcesos = 0;
    public DefaultTableModel modeloTabla = new DefaultTableModel();

    public Proyecto() {
        initComponents();
        lblHora.setOpaque(true);
        lblContadorPrograma.setOpaque(true);
        lblControl.setOpaque(true);
        lblCalendarizador.setOpaque(true);
        lblInterrupcionActiva.setOpaque(true);
        this.setTitle("<Manejador de procesos e interrupciones>");
        this.setResizable(false);
        this.setLocationRelativeTo(null);
        this.getContentPane().setBackground(new Color(242, 242, 242));
        lblNuevo.setIcon(new ImageIcon(getClass().getResource("agregar.png")));
        lblInterrupcionActiva.setVisible(false);

        currentTime.start();
        reduceTimeProcess.start();
        modeloTabla.addColumn("Proceso");
        modeloTabla.addColumn("Inicio");
        modeloTabla.addColumn("Total");
        modeloTabla.addColumn("Restante");
        modeloTabla.addColumn("Fin");
        ControlTiempo.setModel(modeloTabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblNuevo = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        txtDireccionMemoria = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtProcesoPC = new javax.swing.JTextField();
        lblCurrentTime = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstCalendarizador = new javax.swing.JList<>();
        jLabel10 = new javax.swing.JLabel();
        turnoProceso = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        ControlTiempo = new javax.swing.JTable();
        lblContadorPrograma = new javax.swing.JLabel();
        lblControl = new javax.swing.JLabel();
        lblCalendarizador = new javax.swing.JLabel();
        lblInterrupcion = new javax.swing.JLabel();
        lblInterrupcionActiva = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNuevo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoso/agregar.png"))); // NOI18N
        lblNuevo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNuevoMouseClicked(evt);
            }
        });
        getContentPane().add(lblNuevo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 450, 50, 50));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 770, 10));

        jSeparator3.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 10, 550));

        jLabel1.setText("Dirección de Memoria:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));
        getContentPane().add(txtDireccionMemoria, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 104, -1));

        jLabel2.setText("Proceso:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, -1, -1));
        getContentPane().add(txtProcesoPC, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 100, 104, -1));

        lblCurrentTime.setFont(new java.awt.Font("Noto Sans", 0, 48)); // NOI18N
        getContentPane().add(lblCurrentTime, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 50, 282, 66));

        lblHora.setBackground(new java.awt.Color(242, 84, 48));
        lblHora.setForeground(new java.awt.Color(255, 255, 255));
        lblHora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHora.setText("Hora del sistema");
        getContentPane().add(lblHora, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 390, 30));

        lstCalendarizador.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(lstCalendarizador);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 284, 230));

        jLabel10.setText("Turno:");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 440, -1, -1));
        getContentPane().add(turnoProceso, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 470, 146, -1));

        ControlTiempo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Proceso", "Inicio", "Total", "Restante", "Fin"
            }
        ));
        ControlTiempo.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane2.setViewportView(ControlTiempo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 190, 370, 340));

        lblContadorPrograma.setBackground(new java.awt.Color(90, 191, 134));
        lblContadorPrograma.setForeground(new java.awt.Color(255, 255, 255));
        lblContadorPrograma.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblContadorPrograma.setText("Contador de programa");
        getContentPane().add(lblContadorPrograma, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 30));

        lblControl.setBackground(new java.awt.Color(242, 172, 41));
        lblControl.setForeground(new java.awt.Color(255, 255, 255));
        lblControl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblControl.setText("Control de tiempo");
        getContentPane().add(lblControl, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 150, 390, 30));

        lblCalendarizador.setBackground(new java.awt.Color(4, 178, 217));
        lblCalendarizador.setForeground(new java.awt.Color(255, 255, 255));
        lblCalendarizador.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCalendarizador.setText("Calendarizador");
        getContentPane().add(lblCalendarizador, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 380, 30));

        lblInterrupcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/proyectoso/interrupcion.png"))); // NOI18N
        lblInterrupcion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblInterrupcionMouseClicked(evt);
            }
        });
        getContentPane().add(lblInterrupcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 450, 50, 50));

        lblInterrupcionActiva.setBackground(new java.awt.Color(255, 51, 51));
        lblInterrupcionActiva.setForeground(new java.awt.Color(255, 255, 255));
        lblInterrupcionActiva.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblInterrupcionActiva.setText("Interrupción activa");
        getContentPane().add(lblInterrupcionActiva, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, 300, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblNuevoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNuevoMouseClicked
        //Crear el proceso
        this.contadorProcesos++;
        proceso process = new proceso();
        process.setNombre("Proceso " + contadorProcesos);
        process.setHora(lblCurrentTime.getText());
        process.setTiempo(getRandomNumberInRange(5, 10));
        process.setEstado("Listo");
        procesos.add(process);
        /*
                Agrega los elementos de procesos a la lista
         */
        tablaProcesos(String.valueOf(process.getTiempo()));
        actualizarLista();
    }//GEN-LAST:event_lblNuevoMouseClicked

    private void lblInterrupcionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblInterrupcionMouseClicked
        //Generar interrupción
        //reduceTimeProcess

        reduceTimeProcess.stop();
        for (int m = 0; m < procesos.size(); m++) {
            if (procesos.get(m).getEstado().equals("En ejecución")) {
                procesos.get(m).setEstado("Bloqueado");
            }
        }
        actualizarLista();
        lblInterrupcionActiva.setVisible(true);

        int numeroAleatorio = getRandomNumberInRange(100, 1000);
        bandera = true;
        contadorInterrupcion = 0;
        esperar(numeroAleatorio);
        
    }//GEN-LAST:event_lblInterrupcionMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Proyecto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Proyecto().setVisible(true);
            }
        });
    }

    //Hilo (Timer) para ir colocando la hora actual, a razón de 1 segundo
    Timer currentTime = new Timer(1000, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            DateFormat df = new SimpleDateFormat("HH:mm:ss");
            Date fecha = new Date();
            lblCurrentTime.setText(df.format(fecha));
        }
    });

    boolean bandera = false;
    int contadorInterrupcion = 0;

    public void esperar(int numeroAleatorio) {
        Timer a = new Timer(numeroAleatorio * 10, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (bandera && contadorInterrupcion == 1) {
                    bandera = false;
                    String cadena = "Se activó la interrupción por " + numeroAleatorio + " ms.";
                    reduceTimeProcess.start();
                    for (int m = 0; m < procesos.size(); m++) {
                        if (procesos.get(m).getEstado().equals("Bloqueado")) {
                            procesos.get(m).setEstado("En ejecucución");
                        }
                    }
                    actualizarLista();
                    lblInterrupcionActiva.setVisible(false);
                    
                }
                contadorInterrupcion++;
            }
        });
        a.start();
    }

    public void actualizarLista() {
        DefaultListModel modeloLista = new DefaultListModel();
        for (int x = 0; x < procesos.size(); x++) {
            modeloLista.addElement(procesos.get(x).getNombre() + ",  " + procesos.get(x).getEstado());
        }
        lstCalendarizador.setModel(modeloLista);
    }

    // Tabla para mostrar el proceso, cuando inicio, el tiempo total, cuanto resta y cuando termina
    public void tablaProcesos(String tiempoInicio) {
        Object[] object = new Object[5];
        for (int x = 0; x < procesos.size(); x++) {
            object[0] = procesos.get(x).getNombre();
            object[1] = procesos.get(x).getHora();
            object[2] = tiempoInicio;
            object[3] = object[2];
            object[4] = "-";
        }
        //Se ingresa a una lista los procesos
        procesosLista.add(object[0].toString());
        modeloTabla.addRow(object);
    }

    public void setearEstados() {
        for (int x = 0; x < procesos.size(); x++) {
            procesos.get(x).setEstado("Listo");
        }
    }

    //Hilo para ir ejecutando los procesos
    //Disminuye los tiempos y va reduciendo su tiempo
    public int x = 0;
    Timer reduceTimeProcess = new Timer(500, new ActionListener() {
        public void actionPerformed(ActionEvent e) {
            setearEstados();
            actualizarLista();
            int tamaño = ControlTiempo.getRowCount();
            //Reducir el tiempo del proceso en un segundo
            if (x >= procesos.size()) {
                x = 0;
            } else {
                //Colcoar valores
                turnoProceso.setText(procesos.get(x).getNombre());
                txtProcesoPC.setText(procesos.get(x).getNombre());
                //txtDireccionMemoria.setText(Integer.toHexString(System.identityHashCode(procesos.get(x))));
                txtDireccionMemoria.setText(Integer.toHexString(procesos.get(x).hashCode()));

                procesos.get(x).setEstado("En ejecución");
                int tiempoActual = procesos.get(x).getTiempo();
                procesos.get(x).setTiempo(tiempoActual - 1);
                actualizarLista();
                String temp = procesos.get(x).getNombre();
                //For para recorrer la lista de los procesos
                for (int i = 0; i < procesosLista.size(); i++) {
                    // If para comparar el proceso actual con el de la lista y colocar la diferencia de tiempo en la pocision debida
                    if (temp.equals(procesosLista.get(i))) {
                        ControlTiempo.setValueAt(tiempoActual - 1, i, 3);
                    }
                }
                /*
                Agrega los elementos de procesos a la lista
                 */
                if (procesos.get(x).getTiempo() <= 0) {
                    procesos.get(x).setEstado("Finalizado");
                    procesos.remove(x);
                    for (int i = 0; i < procesosLista.size(); i++) {
                        if (temp.equals(procesosLista.get(i))) {
                            ControlTiempo.setValueAt(lblCurrentTime.getText(), i, 4);
                        }
                    }
                    turnoProceso.setText("");
                    txtProcesoPC.setText("");
                    txtDireccionMemoria.setText("");
                    actualizarLista();
                }
                x++;
            }

        }
    });

    private static int getRandomNumberInRange(int min, int max) {
        if (min >= max) {
            throw new IllegalArgumentException("max must be greater than min");
        }

        Random r = new Random();
        return r.nextInt((max - min) + 1) + min;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ControlTiempo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel lblCalendarizador;
    private javax.swing.JLabel lblContadorPrograma;
    private javax.swing.JLabel lblControl;
    private javax.swing.JLabel lblCurrentTime;
    private javax.swing.JLabel lblHora;
    private javax.swing.JLabel lblInterrupcion;
    private javax.swing.JLabel lblInterrupcionActiva;
    private javax.swing.JLabel lblNuevo;
    private javax.swing.JList<String> lstCalendarizador;
    private javax.swing.JTextField turnoProceso;
    private javax.swing.JTextField txtDireccionMemoria;
    private javax.swing.JTextField txtProcesoPC;
    // End of variables declaration//GEN-END:variables
}
